server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://root:pzKFteGkwdjzwTVLcCbIjqPgrvEJFtzQ@metro.proxy.rlwy.net:12543/railway?allowPublicKeyRetrieval=true&useSSL=false
    username: root          # ğŸ‘‰ ì—¬ê¸° ë³¸ì¸ MySQL ì•„ì´ë””ë¡œ ìˆ˜ì • (ë³´í†µ root)
    password: pzKFteGkwdjzwTVLcCbIjqPgrvEJFtzQ # â­ğŸ‘‰ ë°˜ë“œì‹œ ë³¸ì¸ì˜ MySQL ë¹„ë°€ë²ˆí˜¸ë¡œ ë³€ê²½
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update        # ê°œë°œ ë‹¨ê³„ì—ì„œëŠ” update / ìš´ì˜ ë‹¨ê³„ì—ì„œëŠ” none ê¶Œì¥
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  jackson:
    serialization:
      fail-on-empty-beans: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.springframework.web: info
  file:
    name: logs/starbooks.log

# Swagger - Springdoc(OpenAPI3)
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

# JWT ì„¤ì •
jwt:
  issuer: starbooks-app
  secret: "THIS_IS_TEMP_JWT_SECRET_KEY_CHANGE_IT_PRODUCTION_!!!"   # â­ğŸ‘‰ ê¼­! ë‚˜ì¤‘ì— ë” ê¸¸ê³  ë³µì¡í•˜ê²Œ ë³€ê²½í•  ê²ƒ
  expiration-ms: 3600000     # 1ì‹œê°„ (ms)

# Spring Security ê¸°ë³¸ ì„¤ì •
security:
  basic:
    enabled: false

info:
  book:
    api-key: "c7a87ae2a9ef1e6b8ca990cb76cb70b2eba0e975e92476d43b731d4bcf86b74f"

data4library:
  key: "c7a87ae2a9ef1e6b8ca990cb76cb70b2eba0e975e92476d43b731d4bcf86b74f"
